# Generated by Django 4.2.8 on 2024-01-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=100)),
                ('Pprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Pdescription', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('Pimg', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
