# Generated by Django 4.2.8 on 2024-01-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_category_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.user'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_list')),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order_status', models.CharField(choices=[('C', 'confirm'), ('p', 'pending'), ('C', 'ccompleted')], default='p', max_length=1)),
                ('product_list', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.product_list')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order_status', models.CharField(choices=[('c', 'confirm'), ('P', 'pending'), ('C', 'ccompleted')], default='p', max_length=1)),
                ('payment_status', models.BooleanField(default=False)),
                ('shipping_address', models.CharField(max_length=200)),
                ('product_list', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.product_list')),
            ],
        ),
    ]
