# Generated by Django 4.2.8 on 2024-01-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('c', 'confirm'), ('P', 'pending'), ('C', 'completed')], default='p', max_length=1),
        ),
    ]
