# Generated by Django 4.2.8 on 2024-01-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'Male')], max_length=50),
        ),
    ]
